from docx import Document
from docx.shared import Pt, Inches
from datetime import datetime
import os
import uuid
import re

def generate_docx(document_content: str) -> str:
    # Ensure directory exists
    docs_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "generated_docs")
    if not os.path.exists(docs_dir):
        os.makedirs(docs_dir)

    doc = Document()
    
    # Try to parse markdown-like structure
    lines = document_content.split('\n')
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        if line.startswith('# '):
            heading = doc.add_heading(line[2:], level=1)
        elif line.startswith('## '):
            heading = doc.add_heading(line[3:], level=2)
        elif line.startswith('### '):
            heading = doc.add_heading(line[4:], level=3)
        elif line.startswith('- ') or line.startswith('* '):
            doc.add_paragraph(line[2:], style='List Bullet')
        elif re.match(r'^\d+\.\s', line):
            # Numbered list
            doc.add_paragraph(line.split(' ', 1)[1], style='List Number')
        else:
            doc.add_paragraph(line)

    # Add Footer
    section = doc.sections[-1]
    footer = section.footer
    footer_para = footer.paragraphs[0]
    footer_para.text = f"Generated by Autonomous AI Agent on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"

    filename = f"document_{uuid.uuid4().hex[:8]}.docx"
    filepath = os.path.join(docs_dir, filename)
    doc.save(filepath)
    return filename
